version: '3.1'

volumes:
  db-data:
    driver: local

services:

  botload:
    build: ./botload/
    ports:
     - '4000:4000'
    volumes:
        - ./botload:/usr/src/app
    depends_on:
        - db

  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: $DB_DATABASE
        POSTGRES_USER: $DB_USERNAME
        POSTGRES_PASSWORD: $DB_PASSWORD
  
  phpmyadmin:
    image: neimheadh/phppgadmin:latest
    restart: always
    ports:
        - 8080:80
    environment:
        POSTGRES_HOST: $DB_HOST
        POSTGRES_PORT: $DB_PORT
        POSTGRES_USER: $DB_USERNAME
        POSTGRES_PASS: $DB_PASSWORD
    depends_on:
        - db